# Generated by Django 3.2.24 on 2024-02-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
