# Generated by Django 4.2.10 on 2024-02-17 09:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portail", "0004_post_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actualite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250, unique_for_date="publish")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="featured_image/%Y/%m/%d/"
                    ),
                ),
                ("body", ckeditor_uploader.fields.RichTextUploadingField()),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ("-publish",),
            },
        ),
    ]
