# Generated by Django 4.2.10 on 2024-02-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portail", "0005_actualite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualite",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
